name: Handle Issues
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  output-info:
    runs-on: macos-latest
    steps:
      - name: Print GitHub context
        run: echo "${{ toJSON(github.event) }}"
