name: Test project
on: push
jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
            node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies
        run: npm test

  deploy:
    needs: test # this job only starts when the previous one is finished.
    runs-on: macos-latest

    steps:
        - name: Get code
          uses: actions/checkout@v4
  
        - name: Install NodeJs
          uses: actions/setup-node@v4
          with:
              node-version: 18
  
        - name: Install dependencies
          run: npm ci
  
        - name: Build project
          run: npm run build

        - name: Deploy
          run: echo "deploying..."